export interface IAlumno {
  id: number;
  nombres: string;
  apellidos: string;
  fechaNacimiento: string;
  sexo: string;
}

export interface IAlumnoCreateData {
  nombres: string;
  apellidos: string;
  fechaNacimiento: string;
  sexo: string;
}

export interface ICurso {
  id: number;
  nombre: string;
  descripcion: string;
  obligatorio: boolean;
  notas: INotas;
  inscripcionId: number;
}

export interface INotas {
  id: number;
  practica_1: number | null;
  practica_2: number | null;
  practica_3: number | null;
  parcial: number | null;
  final: number | null;
}

export interface IAlumnoDetail extends IAlumno {
  cursos?: ICurso[];
}
// Generated by https://quicktype.io

export interface ISpecificUser extends IAlumno {
  inscripcionesCursos: InscripcionesCurso[];
}

export interface InscripcionesCurso {
  id: number;
  alumnoId: number;
  cursoId: number;
  curso: Curso;
  notas: Notas;
}

export interface Curso {
  id: number;
  nombre: string;
  descripcion: string;
  obligatoriedad: boolean;
  inscripcionesCursos: any[];
}

export interface Notas {
  id: number;
  practica_1: number | null;
  practica_2: number | null;
  practica_3: number | null;
  parcial: number | null;
  final: number | null;
  inscripcionCursoId: number;
}
